[tools]
usage = "latest"
slsa-verifier = "latest"
cosign = "latest"
cargo-binstall = "latest"
eza = "latest"
rust = "latest"
ruby = "latest"
node = "latest"
python = "latest"
uv = "latest"
go = "latest"
fzf = "latest"
hunk = "latest"
bat = "latest"
glow = "latest"
tokei = "latest"
sqlc = "1.30.0"
gh = "latest"

[settings]
activate_aggressive = true
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
compile = false
