cabbrev qw :wq
iab fcihier fichier
iab fcihiers fichiers
iab meme même
iab afficahge affichage
iab dnas dans
iab focntionnement fonctionnement
iab focntion fonction
iab riqsue risque
iab cyle cycle
iab shoudl should
